[build]
command = "yarn build"
publish = "build"

[[redirects]]
from = "https://m.rohmer.rocks/*"
to = "https://matthias.rohmer.rocks/:splat"
status = 301
force = true

[[redirects]]
from = "https://matze.rohmer.rocks/*"
to = "https://matthias.rohmer.rocks/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.rohmer.rocks/*"
to = "https://matthias.rohmer.rocks/:splat"
status = 301
force = true

[[redirects]]
from = "https://rohmer.rocks/*"
to = "https://matthias.rohmer.rocks/:splat"
status = 301
force = true
